server:
  port: 8100

spring:
  application:
    name: leeshop-web-admin
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
    content-type: text/html

dubbo:
  scan:
    base-packages: com.lusifer.leeshop.web.admin.controller
  application:
    id: leeshop-web-admin
    name: leeshop-web-admin
  registry:
    id: zookeeper
    address: zookeeper://192.168.75.130:2181?backup=192.168.75.132:2182,192.168.75.132:2183