spring:
  application:
    name: leeshop-service-search
  datasource:
    druid:
      url: jdbc:mysql://192.168.75.130:3306/leeshop?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      driver-class-name: com.mysql.jdbc.Driver
  data:
    solr:
      host: http://192.168.75.130:8983/solr

mybatis:
    type-aliases-package: com.lusifer.leeshop.domain
    mapper-locations: classpath:mapper/*.xml

dubbo:
  scan:
    base-packages: com.lusifer.leeshop.service.search.api
  application:
    id: leeshop-service-search
    name: leeshop-service-search
  protocol:
    id: dubbo
    name: dubbo
  registry:
    id: zookeeper
    address: zookeeper://192.168.75.130:2181?backup=192.168.75.130:2182,192.168.75.130:2183